"""Generate an interactive HTML map with A* paths using the EXACT same
pipeline as map_runner.py (EDT corridor-centering + corridor-nudge + 
segment safety). Use this to visually validate paths before running in Webots.
"""
import os, sys, math, heapq
import numpy as np

try:
    import plotly.graph_objects as go
except ImportError:
    print("Plotly not found. Installing...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "plotly"])
    import plotly.graph_objects as go

try:
    from scipy.ndimage import distance_transform_edt
except ImportError:
    print("scipy not found. Installing...")
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "scipy"])
    from scipy.ndimage import distance_transform_edt

# ── Configuration  (MUST match map_runner.py exactly) ──
RES         = 0.04
X_MIN, X_MAX = -3.0, 4.0
Y_MIN, Y_MAX = -5.0, 3.0
POISON_COST = 50.0
INFLATE     = 4          # default inflate; adaptive loop tries 4→3→2→1
RDP_TOL     = 0.04
CARVE_R     = 0.22
WALL_PROX_WEIGHT = 10.0  # EDT corridor-centering weight
WALL_PROX_CELLS  = 12    # EDT influence radius in cells

# Path safety thresholds (Issue 2 fix — must match map_runner.py)
NUDGE_ANGLE_DEG = 20.0   # turn ≥ this triggers corridor-center nudge
NUDGE_SEARCH_R  = 6      # nudge search radius (cells) → 24 cm
SAFETY_MIN_DIST = 4      # min wall distance for simplified segments → 16 cm

# Paths
_HERE = os.path.dirname(os.path.abspath(__file__))
PLY_PATH = os.path.normpath(os.path.join(_HERE, "maps", "scene.ply"))
NPZ_PATH = os.path.normpath(os.path.join(_HERE, "maps", "map.npz"))
OUT_HTML = os.path.join(_HERE, "maps", "interactive_map.html")

def _wrap(a):
    while a >  math.pi: a -= 2*math.pi
    while a < -math.pi: a += 2*math.pi
    return a

# ═══════════════════════════════════════════════════════════════════════
#  1. Load PLY
# ═══════════════════════════════════════════════════════════════════════

def load_ply(path):
    """Load raw PLY (only used for reference scatter — NOT for planning)."""
    with open(path) as f:
        lines = f.readlines()
    h = next(i for i, l in enumerate(lines) if l.strip() == 'end_header') + 1
    pts = []
    for l in lines[h:]:
        p = l.split()
        if len(p) >= 3:
            pts.append((float(p[0]), float(p[1]), float(p[2])))
    return np.array(pts)

def extract_walls(pts):
    z = pts[:, 2]
    return pts[(z > 0.03) & (z < 0.55)]


def build_wall_mask_from_ply(pts_world):
    """Clean wall mask generated by projecting 3D point cloud into 2D grid.
    This resolves the missing-wall bugs caused by LiDAR seeing through glass or
    short walls where `map.npz` fails to accumulate them."""
    nx_g = int((X_MAX - X_MIN) / RES)
    ny_g = int((Y_MAX - Y_MIN) / RES)
    out = np.zeros((nx_g, ny_g), dtype=bool)

    if pts_world is None or len(pts_world) == 0:
        return out

    ix = ((pts_world[:, 0] - X_MIN) / RES).astype(int)
    iy = ((pts_world[:, 1] - Y_MIN) / RES).astype(int)
    m = (ix >= 0) & (ix < nx_g) & (iy >= 0) & (iy < ny_g)
    out[ix[m], iy[m]] = True
    
    # Apply a minimal 1-cell dilation to ensure the 2D wall is solid
    # (since the PLY was voxel-downsampled)
    try:
        from scipy.ndimage import binary_dilation
        out = binary_dilation(out, iterations=1)
    except Exception:
        pass
        
    return out


# ═══════════════════════════════════════════════════════════════════════
#  2. Grid with EDT corridor-centering (same as map_runner.py)
# ═══════════════════════════════════════════════════════════════════════

class Grid:
    def __init__(self, wall_input, poison=None):
        """Accepts either a (N, 2+)-array of wall points (legacy) OR a
        precomputed bool wall mask (preferred — fed from npz['occupied'])."""
        self.nx = int((X_MAX - X_MIN) / RES)
        self.ny = int((Y_MAX - Y_MIN) / RES)
        if isinstance(wall_input, np.ndarray) and wall_input.dtype == bool \
                and wall_input.shape == (self.nx, self.ny):
            self.wall = wall_input.copy()
        else:
            self.wall = np.zeros((self.nx, self.ny), dtype=bool)
            for x, y in zip(wall_input[:, 0], wall_input[:, 1]):
                ix, iy = self.w2i(x, y)
                if self.ok(ix, iy):
                    self.wall[ix, iy] = True
        self.wall_orig = self.wall.copy()
        self.poison = poison if poison is not None else np.zeros_like(self.wall)
        self.dist_to_wall = None

    def w2i(self, x, y):
        return int((x - X_MIN) / RES), int((y - Y_MIN) / RES)

    def i2w(self, ix, iy):
        return X_MIN + (ix + 0.5) * RES, Y_MIN + (iy + 0.5) * RES

    def ok(self, ix, iy):
        return 0 <= ix < self.nx and 0 <= iy < self.ny

    def inflate(self, r=INFLATE):
        orig = self.wall.copy()
        for di in range(-r, r + 1):
            for dj in range(-r, r + 1):
                if 0 < math.hypot(di, dj) <= r:
                    self.wall |= np.roll(np.roll(orig, di, 0), dj, 1)
        self._compute_distance_field()

    def _compute_distance_field(self):
        free = ~self.wall
        self.dist_to_wall = distance_transform_edt(free)

    def carve(self, x, y, rm=CARVE_R):
        rc = int(math.ceil(rm / RES))
        cx, cy = self.w2i(x, y)
        for di in range(-rc, rc + 1):
            for dj in range(-rc, rc + 1):
                if math.hypot(di, dj) <= rc:
                    ix, iy = cx + di, cy + dj
                    if self.ok(ix, iy):
                        self.wall[ix, iy] = False
                        self.poison[ix, iy] = False
        self._compute_distance_field()

    def cost(self, ix, iy):
        if not self.ok(ix, iy) or self.wall[ix, iy]:
            return float('inf')
        base = POISON_COST if self.poison[ix, iy] else 1.0
        if self.dist_to_wall is not None:
            d = self.dist_to_wall[ix, iy]
            if d < WALL_PROX_CELLS:
                base += WALL_PROX_WEIGHT * (1.0 - d / WALL_PROX_CELLS)
        return base


# ═══════════════════════════════════════════════════════════════════════
#  3. A* (same as map_runner.py)
# ═══════════════════════════════════════════════════════════════════════

def astar(grid, start, goal):
    si, sj = grid.w2i(*start)
    gi, gj = grid.w2i(*goal)
    if not grid.ok(si, sj) or not grid.ok(gi, gj): return None
    h = lambda i, j: math.hypot(i - gi, j - gj)
    openq = [(h(si, sj), 0.0, si, sj)]
    gscore = {(si, sj): 0.0}
    parent = {}
    closed = set()
    while openq:
        _, g, ci, cj = heapq.heappop(openq)
        if (ci, cj) in closed: continue
        closed.add((ci, cj))
        if ci == gi and cj == gj:
            path = []
            n = (gi, gj)
            while n in parent:
                path.append(grid.i2w(*n))
                n = parent[n]
            path.append(grid.i2w(si, sj))
            path.reverse()
            return path
        for di, dj in [(-1,0),(1,0),(0,-1),(0,1),(-1,-1),(-1,1),(1,-1),(1,1)]:
            ni, nj = ci + di, cj + dj
            c = grid.cost(ni, nj)
            if c == float('inf') or (ni, nj) in closed: continue
            ng = g + math.hypot(di, dj) * c
            if ng < gscore.get((ni, nj), float('inf')):
                gscore[(ni, nj)] = ng
                parent[(ni, nj)] = (ci, cj)
                heapq.heappush(openq, (ng + h(ni, nj), ng, ni, nj))
    return None


# ═══════════════════════════════════════════════════════════════════════
#  4. Path simplification + corridor-centering (same as map_runner.py)
# ═══════════════════════════════════════════════════════════════════════

def _rdp(pts, eps):
    if len(pts) <= 2: return pts
    s, e = np.array(pts[0]), np.array(pts[-1])
    lv = e - s
    ll = np.linalg.norm(lv)
    if ll < 1e-9: return [pts[0], pts[-1]]
    lu = lv / ll
    dmax, idx = 0, 0
    for i in range(1, len(pts) - 1):
        v = np.array(pts[i]) - s
        d = abs(v[0] * lu[1] - v[1] * lu[0])
        if d > dmax:
            dmax, idx = d, i
    if dmax > eps:
        return _rdp(pts[:idx + 1], eps)[:-1] + _rdp(pts[idx:], eps)
    return [pts[0], pts[-1]]


def _nudge_to_center(pts, grid, search_r=NUDGE_SEARCH_R):
    """At sharp turns, nudge waypoint toward the corridor centre.
    Capped at search_r cells displacement; candidate must be inside a corridor."""
    if not hasattr(grid, 'dist_to_wall') or grid.dist_to_wall is None:
        return pts
    MAX_CORRIDOR_DIST = 8
    result = [pts[0]]
    for i in range(1, len(pts) - 1):
        dx1 = pts[i][0] - pts[i - 1][0]
        dy1 = pts[i][1] - pts[i - 1][1]
        dx2 = pts[i + 1][0] - pts[i][0]
        dy2 = pts[i + 1][1] - pts[i][1]
        a1 = math.atan2(dy1, dx1)
        a2 = math.atan2(dy2, dx2)
        turn = abs(_wrap(a2 - a1))
        if turn > math.radians(NUDGE_ANGLE_DEG):
            ix, iy = grid.w2i(*pts[i])
            best_d = 0
            best_ix, best_iy = ix, iy
            for di in range(-search_r, search_r + 1):
                for dj in range(-search_r, search_r + 1):
                    if math.hypot(di, dj) > search_r:
                        continue
                    ni, nj = ix + di, iy + dj
                    if grid.ok(ni, nj) and not grid.wall[ni, nj]:
                        d = grid.dist_to_wall[ni, nj]
                        if d > best_d and d < MAX_CORRIDOR_DIST:
                            best_d = d
                            best_ix, best_iy = ni, nj
            result.append(grid.i2w(best_ix, best_iy))
        else:
            result.append(pts[i])
    result.append(pts[-1])
    return result


def _ensure_segment_clearance(pts, original_path, grid, min_dist=SAFETY_MIN_DIST):
    """Insert midpoints from original A* path if simplified segments clip walls."""
    if not hasattr(grid, 'dist_to_wall') or grid.dist_to_wall is None:
        return pts
    result = [pts[0]]
    for i in range(1, len(pts)):
        dx, dy = pts[i][0] - pts[i - 1][0], pts[i][1] - pts[i - 1][1]
        length = math.hypot(dx, dy)
        n_samples = max(3, int(length / (RES * 0.5)))
        unsafe = False
        for k in range(n_samples + 1):
            t = k / n_samples
            x = pts[i - 1][0] + t * dx
            y = pts[i - 1][1] + t * dy
            ix, iy = grid.w2i(x, y)
            if not grid.ok(ix, iy) or grid.wall[ix, iy]:
                unsafe = True; break
            if grid.dist_to_wall[ix, iy] < min_dist:
                unsafe = True; break
        if unsafe and original_path:
            mid_x = (pts[i - 1][0] + pts[i][0]) / 2
            mid_y = (pts[i - 1][1] + pts[i][1]) / 2
            best = None
            best_score = float('inf')
            for op in original_path:
                oix, oiy = grid.w2i(op[0], op[1])
                if grid.ok(oix, oiy) and grid.dist_to_wall[oix, oiy] >= min_dist:
                    d = math.hypot(op[0] - mid_x, op[1] - mid_y)
                    if d < best_score:
                        best_score = d
                        best = op
            if best:
                result.append(best)
        result.append(pts[i])
    return result


def _split_long_segments(pts, max_seg=0.30):
    """Insert midpoints on any segment longer than max_seg metres."""
    result = [pts[0]]
    for i in range(1, len(pts)):
        dx = pts[i][0] - pts[i - 1][0]
        dy = pts[i][1] - pts[i - 1][1]
        seg_len = math.hypot(dx, dy)
        if seg_len > max_seg:
            n_splits = int(math.ceil(seg_len / max_seg))
            for k in range(1, n_splits):
                t = k / n_splits
                result.append((pts[i - 1][0] + t * dx,
                                pts[i - 1][1] + t * dy))
        result.append(pts[i])
    return result


def simplify(path, grid=None):
    """Simplify A* path: RDP → nudge turns to corridor centres → safety → split."""
    if len(path) <= 2: return path
    original = list(path)
    pts = _rdp(path, RDP_TOL)
    if grid is not None:
        pts = _nudge_to_center(pts, grid)
        pts = _ensure_segment_clearance(pts, original, grid)
    pts = _split_long_segments(pts)
    return pts


# ═══════════════════════════════════════════════════════════════════════
#  5. Main — generate interactive HTML
# ═══════════════════════════════════════════════════════════════════════

def main():
    print("Loading data...")
    if not os.path.isfile(NPZ_PATH):
        print(f"Error: {NPZ_PATH} not found — run teleop first.")
        return
    npz = np.load(NPZ_PATH, allow_pickle=False)

    # ── Hybrid wall loading (PLY + NPZ merged via OR) ──
    # PLY catches walls the 2D LiDAR misses; NPZ catches LiDAR-confirmed walls.
    all_pts = load_ply(PLY_PATH) if os.path.isfile(PLY_PATH) else np.zeros((0, 3))
    wall_pts = extract_walls(all_pts)
    wall_ply = build_wall_mask_from_ply(wall_pts)
    print(f"  PLY: {len(all_pts)} total, {len(wall_pts)} wall pts → {int(wall_ply.sum())} cells")

    # Also load NPZ walls
    nx_g = int((X_MAX - X_MIN) / RES); ny_g = int((Y_MAX - Y_MIN) / RES)
    wall_npz = np.zeros((nx_g, ny_g), dtype=bool)
    src_occ = npz["occupied"].astype(bool)
    if "aux_obstacle" in npz.files:
        src_occ = src_occ | npz["aux_obstacle"].astype(bool)
    sr  = float(npz["resolution"])
    sox = float(npz["origin"][0]); soy = float(npz["origin"][1])
    ii, jj = np.where(src_occ)
    if len(ii) > 0:
        sx = sox + (ii + 0.5) * sr; sy = soy + (jj + 0.5) * sr
        nix = ((sx - X_MIN) / RES).astype(int); niy = ((sy - Y_MIN) / RES).astype(int)
        nm = (nix >= 0) & (nix < nx_g) & (niy >= 0) & (niy < ny_g)
        wall_npz[nix[nm], niy[nm]] = True

    # Merge: any cell either source marks as wall is treated as wall
    wall_mask = wall_ply | wall_npz
    print(f"  NPZ: {int(wall_npz.sum())} cells  |  Hybrid merged: {int(wall_mask.sum())} cells")

    blue   = (float(npz["pillar_blue"][0]),   float(npz["pillar_blue"][1]))
    yellow = (float(npz["pillar_yellow"][0]), float(npz["pillar_yellow"][1]))
    print(f"  BLUE:   ({blue[0]:+.3f}, {blue[1]:+.3f})")
    print(f"  YELLOW: ({yellow[0]:+.3f}, {yellow[1]:+.3f})")

    poison_g = None
    if npz and "poison" in npz.files:
        psrc = npz["poison"].astype(bool)
        sr = float(npz["resolution"])
        sox, soy = float(npz["origin"][0]), float(npz["origin"][1])
        sn = int(npz["cells"])
        nx_g, ny_g = int((X_MAX - X_MIN) / RES), int((Y_MAX - Y_MIN) / RES)
        poison_g = np.zeros((nx_g, ny_g), dtype=bool)
        for si in range(sn):
            for sj in range(sn):
                if psrc[si, sj]:
                    wx, wy = sox + (si + 0.5) * sr, soy + (sj + 0.5) * sr
                    ix, iy = int((wx - X_MIN) / RES), int((wy - Y_MIN) / RES)
                    if 0 <= ix < nx_g and 0 <= iy < ny_g:
                        poison_g[ix, iy] = True

    start = (0.0, 0.0)

    # ── Leg 1: START → BLUE (adaptive inflation) ──
    print("Calculating path 1: START -> BLUE (adaptive inflation)")
    direct_dist1 = math.hypot(start[0] - blue[0], start[1] - blue[1])
    pb = None
    grid1 = None
    for inf_r in [INFLATE, 3, 2, 1]:
        grid1 = Grid(wall_mask, poison_g)
        grid1.inflate(r=inf_r)
        grid1.carve(start[0], start[1])
        grid1.carve(blue[0], blue[1])
        grid1.carve(yellow[0], yellow[1])
        pb = astar(grid1, start, blue)
        if pb is None:
            print(f"  inflate={inf_r}: no path, trying smaller...")
            continue
        pb = simplify(pb, grid1)
        pl = sum(math.hypot(b[0]-a[0], b[1]-a[1]) for a, b in zip(pb[:-1], pb[1:]))
        if pl > direct_dist1 * 5.0:
            print(f"  inflate={inf_r}: path {pl:.2f}m > 5x direct, trying tighter...")
            pb = None; continue
        print(f"  ✓ inflate={inf_r}: {len(pb)} waypoints, {pl:.2f}m")
        for i, (wx, wy) in enumerate(pb):
            print(f"    WP{i}: ({wx:+.4f}, {wy:+.4f})")
        break

    # ── Leg 2: BLUE → YELLOW (adaptive inflation) ──
    print("Calculating path 2: BLUE -> YELLOW (adaptive inflation)")
    direct_dist2 = math.hypot(blue[0] - yellow[0], blue[1] - yellow[1])
    py = None
    grid2 = None
    for inf_r in [INFLATE, 3, 2, 1]:
        grid2 = Grid(wall_mask, poison_g)
        grid2.inflate(r=inf_r)
        grid2.carve(blue[0], blue[1])
        grid2.carve(yellow[0], yellow[1])
        py = astar(grid2, blue, yellow)
        if py is None:
            print(f"  inflate={inf_r}: no path, trying smaller...")
            continue
        py = simplify(py, grid2)
        pl2 = sum(math.hypot(b[0]-a[0], b[1]-a[1]) for a, b in zip(py[:-1], py[1:]))
        if pl2 > direct_dist2 * 8.0:
            print(f"  inflate={inf_r}: path {pl2:.2f}m > 8x direct, trying tighter...")
            py = None; continue
        print(f"  ✓ inflate={inf_r}: {len(py)} waypoints, {pl2:.2f}m")
        for i, (wx, wy) in enumerate(py):
            print(f"    WP{i}: ({wx:+.4f}, {wy:+.4f})")
        break

    # ── Generate Interactive Plot ──
    print("Generating interactive plot...")
    fig = go.Figure()

    # Solid Walls (contours from raw uninflated grid)
    try:
        from skimage import measure
    except ImportError:
        print("scikit-image not found. Installing...")
        import subprocess
        subprocess.check_call([sys.executable, "-m", "pip", "install", "scikit-image"])
        from skimage import measure

    # Contours from the CLEAN npz wall mask, not the noisy PLY scatter.
    raw_grid = Grid(wall_mask)
    contours = measure.find_contours(raw_grid.wall.astype(float), 0.5)
    for n, contour in enumerate(contours):
        wx = X_MIN + (contour[:, 0] + 0.5) * RES
        wy = Y_MIN + (contour[:, 1] + 0.5) * RES
        fig.add_trace(go.Scatter(
            x=wx, y=wy, mode='lines',
            line=dict(color='black', width=3),
            name='Solid Walls', showlegend=(n == 0),
            hovertemplate='Wall Edge<br>X: %{x:.3f}<br>Y: %{y:.3f}<extra></extra>'
        ))

    # Poison Zones
    if poison_g is not None and grid1 is not None:
        px, py_pts = [], []
        for i in range(poison_g.shape[0]):
            for j in range(poison_g.shape[1]):
                if poison_g[i, j]:
                    wx, wy = grid1.i2w(i, j)
                    px.append(wx)
                    py_pts.append(wy)
        fig.add_trace(go.Scatter(
            x=px, y=py_pts, mode='markers',
            marker=dict(size=4, color='green', opacity=0.1),
            name='Poison Cells', hoverinfo='none'
        ))

    # Path: START → BLUE
    if pb:
        xs, ys = zip(*pb)
        fig.add_trace(go.Scatter(
            x=xs, y=ys, mode='lines+markers+text',
            line=dict(color='dodgerblue', width=4),
            marker=dict(size=8, color='dodgerblue'),
            text=[f"W{i}" for i in range(len(pb))],
            textposition="top right",
            name='Path -> BLUE',
            hovertemplate='WP%{text}<br>X: %{x:.3f}<br>Y: %{y:.3f}<extra></extra>'
        ))

    # Path: BLUE → YELLOW
    if py:
        xs, ys = zip(*py)
        fig.add_trace(go.Scatter(
            x=xs, y=ys, mode='lines+markers+text',
            line=dict(color='orangered', width=4),
            marker=dict(size=8, color='orangered'),
            text=[f"W{i}" for i in range(len(py))],
            textposition="top right",
            name='Path -> YELLOW',
            hovertemplate='WP%{text}<br>X: %{x:.3f}<br>Y: %{y:.3f}<extra></extra>'
        ))

    # Key Locations
    fig.add_trace(go.Scatter(
        x=[start[0]], y=[start[1]], mode='markers+text',
        marker=dict(size=14, color='green', symbol='triangle-up',
                    line=dict(width=2, color='darkgreen')),
        text=["START"], textposition="bottom center", name="Start",
        hovertemplate='START<br>X: %{x:.3f}<br>Y: %{y:.3f}<extra></extra>'
    ))
    fig.add_trace(go.Scatter(
        x=[blue[0]], y=[blue[1]], mode='markers+text',
        marker=dict(size=14, color='blue', line=dict(width=2, color='darkblue')),
        text=["BLUE"], textposition="bottom center", name="Blue Pillar",
        hovertemplate='BLUE<br>X: %{x:.3f}<br>Y: %{y:.3f}<extra></extra>'
    ))
    fig.add_trace(go.Scatter(
        x=[yellow[0]], y=[yellow[1]], mode='markers+text',
        marker=dict(size=14, color='gold', line=dict(width=2, color='darkgoldenrod')),
        text=["YELLOW"], textposition="bottom center", name="Yellow Pillar",
        hovertemplate='YELLOW<br>X: %{x:.3f}<br>Y: %{y:.3f}<extra></extra>'
    ))

    fig.update_layout(
        title='Interactive 2D Grid & Paths — EDT Corridor-Centered (Hover for coordinates)',
        xaxis_title='X Coordinate (m)',
        yaxis_title='Y Coordinate (m)',
        xaxis=dict(scaleanchor="y", scaleratio=1),
        hovermode='closest',
        width=1000, height=800,
        plot_bgcolor='white'
    )
    fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightGray')
    fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightGray')

    os.makedirs(os.path.dirname(OUT_HTML), exist_ok=True)
    fig.write_html(OUT_HTML)
    print(f"\nInteractive map saved to {OUT_HTML}")
    print("Open in browser to validate paths before running in Webots.")

if __name__ == "__main__":
    main()
